FROM registry.access.redhat.com/ubi10/ubi-minimal

LABEL org.opencontainers.image.authors="CodeReady Containers <devtools-cdk@redhat.com>"

RUN microdnf install -y openssh-clients git zip bash jq findutils python3 pip tar \
    && pip install git+https://github.com/apache/otava.git \
    && pip install --no-cache-dir requests opensearch-py pandas matplotlib jinja2\
    && microdnf clean all

COPY . /opt/


